### ISSUE TITLE
.tex files not converting to pngs

### ISSUE THREAD

**Issue by trauvi** [XIV-Tools/TexToolsModExtractor#1]
Only occurs when extracting a mod that features a model. I wanted access to the texture of an eyebrow mod, that so happened to come attached to a beard/model mod. I extracted fine, but the .tex do not convert to .png in the texture folder. I assume this is due to model extract not being complete yet.

**Comment by Luminiari** [comment]
Thank you for reporting this issue! It has now been resolved, and a [new version](https://github.com/XIV-Tools/TexToolsModExtractor/releases/tag/1.0.1) of the tool has been released.
